### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by gregmacfarlane** [tfresource/website#253]
We currently are showing [three security alerts](https://github.com/tfresource/website/network/alerts) on TF Resource. Do we need to update or ditch those dependencies? Or can we simply ignore them?

**Comment by billyc** [comment]
Hi Greg,

I will update the site to use the fixed libraries, thanks for the note. In
general we are very low risk because we're not running any server software.
There's nothing for an attacker to infect. That was a big motivation for
the switch to a static site.

But it's still good to keep things updated.

- Billy

**Comment by billyc** [comment]
fixed
