### ISSUE TITLE
🛠️ Chore: update teams membership and privileges to be consistent with committee membership

### ISSUE THREAD

**Issue by e-lo** [tfresource/website#369]
As a subcommittee member, I would like to be able to assign issues, issue labels, issue milestones, edit issues to add detail and pull-request reviews.

## The way it is
I do not have any of these privileges as a subcommittee member

## The way it should be
Create a github "team" of committee members and assign privileges to assign issues, issue labels, issue milestones and pull-request reviews.

**Comment by gregmacfarlane** [comment]
It's tricky because subcommittees do not actually have members. But we have a group of people who participates regularly, and we can give the appropriate membership to those people. 

One of the things we talked about at the December meeting was that with only one repository, creating a team and managing the team is exactly the same as giving access to one repository directly (which is what we have done). But I have sent membership invitations to most of our regular contributors, and we will go from there.

**Comment by billyc** [comment]
Minor rant: Is there a way to turn off/disable the emoji in the email
subject lines of these "chore" emails?  They clutter and distract my email
inbox. The automated emails describing chores are the very lowest priority
things I have to triage, and yet they jump out as most important because of
the annoying subject-line emoji.
